#!/bin/bash

readonly program="$(basename "${0}")"

function usage {
  echo "
    usage: ${program} <--server|--smtp> [project_directory]

    options:
      --server     Send emails from the server the script is on
      --smtp       Send emails from SMTP server
      -h, --help   Show this help
  " | sed -E 's/^ {4}//'
}

# Available flags
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    --server)
      email_via='server'
      ;;
    --smtp)
      email_via='smtp'
      ;;
    -*)
      syntax_error "unrecognized option: ${1}"
      ;;
    *)
      break
      ;;
  esac
  shift
done

if [[ -z "${email_via}" ]]; then
  echo 'You need to specify a flag for the method to send emails'
  usage
  exit 1
fi

root_directory="$([[ -n "${1}" ]] && echo "${1}" || pwd)"

# Start getting what we need
if [[ -d "${root_directory}" ]]; then
  cd "${root_directory}" || exit 1
else
  echo 'Chosen directory does not exist'
  exit 1
fi

# Get PHPMailer
mkdir -p "send_email"
git clone 'https://github.com/PHPMailer/PHPMailer.git' 'send_email/PHPMailer'

# Get email script
if [[ "${email_via}" == 'server' ]]; then
  curl --silent 'https://raw.githubusercontent.com/vitorgalvao/setup-php-contact-form/master/send_from_server.php' --output 'send_email/send_email.php'
else
  curl --silent 'https://raw.githubusercontent.com/vitorgalvao/setup-php-contact-form/master/send_from_smtp.php' --output 'send_email/send_email.php'
fi

# Get example form
curl --silent "https://raw.githubusercontent.com/vitorgalvao/setup-php-contact-form/master/example_contact_form.html" | pbcopy

echo 'PHPMailer (and related scripts) are in /send_email/'
echo 'Template code (with example form and links to necessary scripts) was copied to your clipboard'
echo 'You will need to edit /send_email/send_email.php to complete the appropriate options'
